services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_pass
      POSTGRES_DB: exam_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://exam_user:exam_pass@db:5432/exam_db
      SECRET_KEY: super-secret-key
    ports:
      - "5000:5000"
